# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-starship

# >> macros
# << macros

Summary:    Starship
Version:    1.0
Release:    1
Group:      Qt/Qt
License:    GPL
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-starship.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(timed-qt5)
BuildRequires:  pkgconfig(mpris-qt5)
BuildRequires:  desktop-file-utils

%description
Short description of my Sailfish OS Application


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_bindir}/harbour-asteroidsyncserviced
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_libdir}/qt5/qml/org/asteroid/syncservice/libasteroidsyncserviceplugin.so
%{_libdir}/qt5/qml/org/asteroid/syncservice/qmldir
%{_userunitdir}/harbour-asteroidsyncserviced.service
# >> files
# << files
